apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagetest-deployment
  namespace: storagetest-ns
  labels:
    app: storagetest
spec:
  selector:
    matchLabels:
      app: storagetest
  template:
    metadata:
      labels:
        app: storagetest
    spec:
      containers:
        - name: storagetest
          image: ghcr.io/stenvik/home:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: storagetest-svc
  namespace: storagetest-ns
spec:
  selector:
    app: storagetest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: storagetest-lb-svc
#   namespace: storagetest-ns
#   annotations:
#     metallb.universe.tf/address-pool: default
# spec:
#   type: LoadBalancer
#   selector:
#     app: storagetest
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: storagetest-ir
  namespace: storagetest-ns
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`storagetest`)
      services:
        - name: storagetest-svc
          port: 3000